print("Hello, welcome to the banking portal.")
print("In this portal, you can handle all your banking needs.")
print("Please enter a selection from the following menu")
print("Type Login to login")
print("Type Quit to quit")
input("Enter Login or Quit: ")
