print("starting...")
#raise ValueError("This is a custom ValueError")
#raise TypeError("This is a raised TypeError.")
#raise ZeroDivisionError("I raised this ZeroDivisionError.")
print("...ending")
